import { tool } from 'ai';
import * as z from 'zod';

import {
  createSalesInvoice,
  getSalesInvoiceById,
  getSalesInvoicesByCompanyId,
  updateSalesInvoice,
} from '@/server/sales-invoice/sales-invoice.service';
import { decimalStringSchema, runTool } from '@/lib/utils';

const salesInvoiceItemSchema = z.object({
  productId: z.number().int().positive(),
  quantity: decimalStringSchema,
  unitPrice: decimalStringSchema,
});

export function createSalesInvoiceTools(companyId: number) {
  return {
    listSalesInvoices: tool({
      description:
        'List sales invoices for the current company. Use this tool when the user asks to list or inspect sales invoices. Use current tool results to identify a specific invoice. Do not guess invoice IDs.',

      inputSchema: z.object({}),

      execute: () =>
        runTool(
          'listSalesInvoices',
          'Sales invoices could not be retrieved.',
          async () => {
            const invoices = await getSalesInvoicesByCompanyId(companyId);

            return invoices.map((invoice) => ({
              id: invoice.id,
              customerId: invoice.customerId,
              warehouseId: invoice.warehouseId,
              invoiceNumber: invoice.invoiceNumber,
              currency: invoice.currency,
              status: invoice.status,
              subtotal: invoice.subtotal,
              discount: invoice.discount,
              tax: invoice.tax,
              total: invoice.total,
              issueDate: invoice.issueDate?.toISOString(),
              dueDate: invoice.dueDate?.toISOString(),
              notes: invoice.notes,
            }));
          },
        ),
    }),

    getSalesInvoice: tool({
      description:
        'Get one sales invoice by numeric invoice ID. Use this tool when the user wants to inspect a specific sales invoice and its ID is known or has been resolved from current invoice results. Do not guess the ID.',

      inputSchema: z.object({
        invoiceId: z.number().int().positive(),
      }),

      execute: ({ invoiceId }) =>
        runTool(
          'getSalesInvoice',
          'Sales invoice could not be retrieved.',
          async () => {
            const invoice = await getSalesInvoiceById(companyId, invoiceId);

            if (!invoice) {
              return {
                found: false,
              };
            }

            return {
              found: true,
              invoice: {
                id: invoice.id,
                customerId: invoice.customerId,
                warehouseId: invoice.warehouseId,
                invoiceNumber: invoice.invoiceNumber,
                currency: invoice.currency,
                status: invoice.status,
                subtotal: invoice.subtotal,
                discount: invoice.discount,
                tax: invoice.tax,
                total: invoice.total,
                issueDate: invoice.issueDate?.toISOString(),
                dueDate: invoice.dueDate?.toISOString(),
                notes: invoice.notes,
              },
            };
          },
        ),
    }),

    createSalesInvoice: tool({
      description:
        'Create a sales invoice for the current company. Use this tool only when the user explicitly asks to create a sales invoice. The customer, warehouse, and at least one invoice item are required. Each item requires a product ID, quantity, and unit price. Discount, tax, due date, issue date, and notes are optional. Do not invent customers, warehouses, products, quantities, prices, or other missing user-provided information. The invoice number and currency are generated by the system and must not be provided by the model. Creating the invoice also creates its sales stock movements and decreases the corresponding warehouse stock, so do not separately decrease warehouse stock for the same sale.',

      inputSchema: z.object({
        customerId: z.number().int().positive(),

        warehouseId: z.number().int().positive(),

        discount: decimalStringSchema.optional(),

        tax: decimalStringSchema.optional(),

        issueDate: z.iso.datetime().optional(),

        dueDate: z.iso.datetime().optional(),

        notes: z.string().trim().max(1000).optional(),

        items: z.array(salesInvoiceItemSchema).min(1).max(100),
      }),

      execute: (invoiceData) =>
        runTool(
          'createSalesInvoice',
          'Sales invoice could not be created.',
          async () => {
            const invoice = await createSalesInvoice(companyId, {
              ...invoiceData,

              issueDate: invoiceData.issueDate
                ? new Date(invoiceData.issueDate)
                : undefined,

              dueDate: invoiceData.dueDate
                ? new Date(invoiceData.dueDate)
                : undefined,
            });

            return {
              invoice: {
                id: invoice.id,
                customerId: invoice.customerId,
                warehouseId: invoice.warehouseId,
                invoiceNumber: invoice.invoiceNumber,
                currency: invoice.currency,
                status: invoice.status,
                subtotal: invoice.subtotal,
                discount: invoice.discount,
                tax: invoice.tax,
                total: invoice.total,
                issueDate: invoice.issueDate?.toISOString(),
                dueDate: invoice.dueDate?.toISOString(),
              },
            };
          },
        ),
    }),

    markSalesInvoiceAsPaid: tool({
      description:
        'Mark an existing sales invoice as paid. Use this tool only when the user explicitly asks to mark a sales invoice as paid. The invoice ID must identify the intended invoice. Cancelled invoices cannot be modified, and a paid invoice cannot be paid again. Do not use this tool to cancel an invoice.',

      inputSchema: z.object({
        invoiceId: z.number().int().positive(),
      }),

      execute: ({ invoiceId }) =>
        runTool(
          'markSalesInvoiceAsPaid',
          'Sales invoice could not be marked as paid.',
          async () => {
            const invoice = await updateSalesInvoice(companyId, invoiceId, {
              status: 'PAID',
            });

            if (!invoice) {
              return {
                updated: false,
                reason: 'Sales invoice not found.',
              };
            }

            return {
              invoice: {
                id: invoice.id,
                invoiceNumber: invoice.invoiceNumber,
                status: invoice.status,
                total: invoice.total,
                currency: invoice.currency,
              },
            };
          },
        ),
    }),
  };
}
